### ISSUE TITLE
CDN Solution

### ISSUE THREAD

**Issue by scooooooooby** [NYPL/nypl-design-system#11]
We know that we'll want some sort of CDN solution for people who want to pull in the design library whole-hog. We'll need to understand:

- [ ] Is this just CSS, or also JS? Are those shipped separately?
- [ ] How is react code vs. vanillaJS shipped in the CDN?

**Comment by EdwinGuzman** [comment]
You could link to the unpkg links (automatically pushes through npm and is widely used):

- https://unpkg.com/@nypl/design-system-react-components/dist/design-system-react-components.min.js
- https://unpkg.com/@nypl/design-system-react-components/dist/styles.css

Those are the master links so it'll redirect to the latest version -- something like `https://unpkg.com/@nypl/design-system-react-components@0.9.1/dist/design-system-react-components.min.js` with `@0.9.1` in the URL.

It'd be nice to have a working demo of this somewhere like codepen.io.

**Comment by helenvholmes** [comment]
@EdwinGuzman whoa, neat! This feels like a great thing to add to the README + spin up a Codepen for. Let's try and get this in next sprint.

**Comment by EdwinGuzman** [comment]
I tried playing around with codepen but had trouble importing in any library (like react). But yes, it'd be worth investigating and setting up an example with it.

**Comment by helenvholmes** [comment]
This is as far as I got with Codepen and the unpkg CDN: https://codepen.io/scoooooooby/pen/wvGzebO?editors=0010
