### ISSUE TITLE
Bem doesn't seem right for modifiers with no blocknames

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#117]
### Screenshot of component in your project:
![Screen Shot 2020-04-17 at 3 28 05 PM](https://user-images.githubusercontent.com/3579472/79606733-10135500-80c0-11ea-99ad-1c88f3b05f3b.png)

### Description of issue:
If there is no blockName, the underscores should be removed.

### Description of desired behavior:
A class with only a modifier should appear like so:

`.classname--modifier`

**Comment by helenvholmes** [comment]
Please also include the unit tests for this.
