### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by scooooooooby** [NYPL/nypl-design-system#12]
Tests!  What kind of tests get written, and where do they live?  

- [ ] CSS code
- [ ] vanillaJS code
- [ ] React code

My instinct is to separate them, but I’m coming from separation-of-concern-world.  In component-world, do they live in the component folder with the js/css/twig/etc?  React-world has componentized tests that check, eg: “Does a field exist and does it accept input?” - is there a way to write tests like that in twig world?  Are those tests written in JS or PHP?

**Comment by helenvholmes** [comment]
Some relevant decisions made in #29.

**Comment by helenvholmes** [comment]
[Ongoing working doc](https://docs.google.com/document/d/1wTUo7PCZMmkjRZ96WXQ-M3gUKJGTPxwV7MDf8nCrtwo/edit?ts=5db6f091#heading=h.ndkaltoz9q6a).
