### ISSUE TITLE
Links should have LinkTypes just like Buttons do

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#122]
### Description of issue:
We have UnderlineLink, IconLink, and Links that look like buttons (Edition Card).  We should apply treatment the way that we do to Buttons, where we use "ButtonTypes".

**Comment by hokei** [comment]
Related issue - iconLink should apply the margin between icon and text without passing in `iconModifiers={["left"]}` separately

**Comment by helenvholmes** [comment]
For accessibility reasons I'd like to no longer ship Links without underlines in the Design System. (See [docs](https://www.w3.org/TR/WCAG21/#use-of-color).)
