### ISSUE TITLE
Use a code formatter like prettier

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#135]
### Original ticket description
I think we're all still using different code formatters.  Now that we've got more people on this, let's make sure we're all using the same one.  Perhaps https://prettier.io/ ?

### Ticket description
- Implement [prettier](https://prettier.io/) in our React library
- Use prettier's default settings

**Comment by helenvholmes** [comment]
Agreed, we should be using Prettier.

**Comment by M0nica** [comment]
@scooooooooby  @hokei What do you all think about the default Prettier config?

```json
{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": false,
  "singleQuote": true
}
```

Do we always/never want arrow function parenthesis? The default is always https://prettier.io/docs/en/options.html#arrow-function-parentheses

You can view the config options here: https://prettier.io/docs/en/options.html

**Comment by helenvholmes** [comment]
@M0nica based on our Slack conversation, sounds like we're all fine with the defaults.
