### ISSUE TITLE
Figma Storybook Add-on

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#143]
We'd like to get Figma's [Storybook Add-on](https://www.figma.com/resources/extensions-and-apis/storybook-figma-addon/) integrated.

**Comment by M0nica** [comment]
this looks cool -- are there any figma files we'd want to add to stories at the moment?

**Comment by helenvholmes** [comment]
The UX team is working on creating all of them, but here are a couple of frames to have something to link to:

[Buttons Primary](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Master?node-id=14972%3A0)

[Buttons Secondary](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Master?node-id=14972%3A143)
