### ISSUE TITLE
How do we define our version numbers?

### ISSUE THREAD

**Issue by scooooooooby** [NYPL/nypl-design-system#16]
versions correspond to built to a spec, or bug fix. What's a breaking change across:

- react
- twig
- styles
- icons

## Known breaking changes
- Moving the location of a component

## Known patch changes

[Working doc](https://docs.google.com/document/d/1_ZAw2aB-SHMemXXKJ_ZQ0m3Eu2FY5sIxcGusQ5uF92g/edit?usp=sharing)

**Comment by helenvholmes** [comment]
Related to #10.

**Comment by hokei** [comment]
One thing that definitely is a breaking change - moving the location of any components.

**Comment by helenvholmes** [comment]
Closing this out.
