### ISSUE TITLE
Re-save all JS files now that we have Prettier

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#166]
Should help out with PRs in the future.

**Comment by M0nica** [comment]
@scooooooooby  Should this only include files within /react-components or throughout the whole system?

**Comment by helenvholmes** [comment]
@M0nica Just within `react-components` for now, I think.

**Comment by M0nica** [comment]
This was resolved when the component file structure was flattened in https://github.com/NYPL/nypl-design-system/pull/174
