### ISSUE TITLE
Missing Tests for Unordered List

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#171]
### Component in question:
Unordered List

### Description of issue:
This component doesn't have any tests. To fix this issue, please add tests.

**Comment by M0nica** [comment]
@scooooooooby there are missing tests for UnorderedList. Is there additional coverage that should be added in this ticket or should this ticket be closed?

Current test coverage: https://github.com/NYPL/nypl-design-system/blob/development/src/react-components/src/__tests__/components/UnorderedList-test.tsx

**Comment by helenvholmes** [comment]
@M0nica I opened this ticket thinking that there weren't _any_ tests for Unordered List... looks like that was incorrect. Thanks for flagging, Monica. I think we can close this out.
