### ISSUE TITLE
Rework Research Now Search Header

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#178]
### Component in question:
Research Now Search Header

### Description of issue:
- Component name should be more generic. "Search Header", or "Header with Search Bar"
- Title in header should be generic, taking text or potentially an image

**Comment by M0nica** [comment]
@scooooooooby should this just be renamed to Header with Search and use a generic/placeholder logo instead?

**Comment by helenvholmes** [comment]
@M0nica I think that's a good suggestion. Let's move forward with that for this ticket. I'll update the ticket description.

**Comment by helenvholmes** [comment]
Part of #220

**Comment by helenvholmes** [comment]
Closed via #274.
