### ISSUE TITLE
Storybook "Show Info" button should not interfere with the stories themselves

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#183]
### Description of issue:
Currently, Storybook's "More Info" button sits on top of the component 
![Screen Shot 2020-05-28 at 10 11 37 AM](https://user-images.githubusercontent.com/3579472/83152289-a5e0cd80-a0cb-11ea-927a-cdfa13a39e07.png)

This can obscure bugs that we don't catch until later 
![Screen Shot 2020-05-28 at 10 12 09 AM](https://user-images.githubusercontent.com/3579472/83152348-b6914380-a0cb-11ea-9984-3af0494ccaf2.png)

**Comment by helenvholmes** [comment]
Hm, that "+" icon is looking mighty funky too 🤔

**Comment by hokei** [comment]
that's fixed in https://github.com/NYPL/nypl-design-system/pull/185, the funkiness what made the info button clearly an issue haha

**Comment by M0nica** [comment]
I'm not sure yet when I can work on this story so I unassigned myself for now in-case anyone else wants to pick up. I started looking into it a bit and saw some GitHub issues (https://github.com/storybookjs/storybook/issues/1147#issuecomment-524883667) that suggested that the `addon-docs` https://www.npmjs.com/package/@storybook/addon-docs was created to replace the info addon. 

Based on what I've seen so far I'd recommend considering replacing the info addon with the addon docs as the info addon seems to have limited ability to customize positioning.  I believee additional configuration needs to be done  after the initial setup to ensure that the addon docs can automatically parse the TypeScript types for each story.

**Comment by helenvholmes** [comment]
@M0nica that's a good suggestion, and makes a lot of sense. I think for the documentation add-on we might want to pull in the content for it from Airtable, which powers Metronome (which in turn adds a layer of complication). I don't think it's a hardcore to-do for this sprint.

**Comment by helenvholmes** [comment]
Captured removing the info button in #144, so closing this out.
