### ISSUE TITLE
Compile .tsx files so they can be used in a javascript repo

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#19]
Right now, the design system is trying to re-purposes as much of the Reuseable-Components repo as possible, which means it is pulling in .tsx components.  

But, RN right now doesn’t support typescript, and there are no plans to make it do so in the future.  If we could make it work, I'd prefer to write design system components in TS rather than JS, though! 

Is it reasonable to compile everything in design-system-react-components as JS and publish it as a separate NPM module?  Are there more standard ways to handle this problem?

**Comment by EdwinGuzman** [comment]
It sounds reasonable to just use typescript and tsconfig to compile into `lib/` and not need webpack (tslint is not necessary but useful and it doesn't help compile). Storybook does have its own webpack file so the loaders just working there sounds fine.

Have a `prepublishOnly` npm task which will compile your code and push it to npm when you run `npm publish`. This will publish the `/react-components` subfolder as its own package which will include its source and lib folder. I think there may be some misunderstanding if you're asking about publishing the root and then also the lib folder, unless if the "root" is the main folder that contains all the subfolders. If by "root" you mean the `/react-components`, then that's not necessary to publish twice (and if you do you'll have version conflicts). Hope that makes sense.

**Comment by hokei** [comment]
Yes, that does!  That's super helpful, thank you!

**Comment by helenvholmes** [comment]
Closed via #39.
