### ISSUE TITLE
Search Result List Story

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#199]
### Component in question:
- UnorderedList

### Description of issue:
- It would be great to show an example of UnorderedList being used to show a list of search result items, showing if/when pagination appears.

**Comment by hokei** [comment]
SearchResultItem should not be a DS element.  It's a DS Heading, Link and Card element.  It should be implemented on the consumer end.  

At a high level, `List` (currently `UnorderedList`) is a wrapper element.  There should not be elements for specific lists of specific things - rather, those things should exist as stories (or examples) under the `List` element

**Comment by helenvholmes** [comment]
Updated the ticket description accordingly, will make a new ticket for retiring SearchResultItem

**Comment by hokei** [comment]
https://nypl.github.io/nypl-design-system/storybook/storybook-static/react/index.html?path=/story/unorderedlist--search-results-list this is already done

**Comment by helenvholmes** [comment]
@hokei Thanks Crystal, music to my ears. Sorry for the Github email spam
