### ISSUE TITLE
Create a more generic Card component

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#206]
- optional 2 columns or 3
- optional top content
- probably optional bottom content
- all of that is generic jsx

**Comment by kristojorg** [comment]
One question here: what would the card itself enforce if all of these are optional? Spacing between the columns? Would it be more useful to simply have a `Card` component that does the border and maybe margins, and then takes whatever children you want to give it?

**Comment by hokei** [comment]
I think there's a strong case that `card` should be a wrapper, like `Unordered List` and `Modal` are ... 
Depending on how they're used though, it might be good for `card` to have helpers, such as `two-column`, `three-column`, etc 

I think the best way to move forward here could be to create a `Card` component that is just a wrapper, and refactor `EditionCard` to use the `Card component`.  How to remove `EditionCard` from design system is a thing that would come later, when we have a better sense of which patterns are very often used (and therefore should belong here) and which patterns are one-offs.

**Comment by helenvholmes** [comment]
i think it makes sense to keep some three column catalog item component from the NYPL perspective—while the styling has been different every time, the component seems to be cropping up over and over. With a generic card that could probably just be captured as stories.

**Comment by helenvholmes** [comment]
@kristojorg, is it okay if we assign this to you?

**Comment by kristojorg** [comment]
That makes sense, but would you rather then make a `Card` component and then some kind of `Columns` component that takes `Column` children and applies the right spacing? EG:

```
<Card>
  <Columns >
    <Column size="1">content</Column>
    <Column size="3">content</Column>
  </Columns>
</Card>
```

**Comment by kristojorg** [comment]
Yea I can contribute the `Card` component at least, but not sure at what point in my development I'll get to it

**Comment by hokei** [comment]
I think it might be confusing to have `Column` be a separate component, since it'll only be used in `Card`.  It would imply that `Card` has an internal grid system which might be true, but also might get pretty complicated.  I expect NYPL will only have one or two commonly used card layouts, and importantly, I don't think that we'd have different two-column cards that used differing internal column widths.  

I think it might be ok for Card to take prop `content` of an array of JSX elements.  If you put in one JSX element, it'll fill up the whole thing, if you put in two or three, it'll split it accordingly, and if you want to put in more than that, or do anything fancy, you can do it yourself by wrapping everything into one JSX element.  

`<Card content=[<JSX.Element>, <JSX.Element>] />`

**Comment by kristojorg** [comment]
How would you then determine how much space each column should get? Or would that not be configurable on a per-card basis? Basically what I'm trying to do is allow the `Card` itself to be used separately if all you need is the border and background and want to define the children yourself.

Personally, I generally favor composing components over passing an array of content, but of course that's up to you. It just fits better into the XML syntax to me. You could, for reference use the same logic you have with children columns, even if they're just for the card (and therefore nested on the card component):
```
<Card>
    <Card.Column size="1">content</Card.Column>
    <Card.Column size="3">content</Card.Column>
</Card>
```
It could then be used generically as well, with custom children and no columns:
```
<Card>children</Card>
```
But again, up to y'all what patterns you want to use for your APIs.

**Comment by hokei** [comment]
Oh yes, that works a lot better than arrays!  That seems great to me.

**Comment by helenvholmes** [comment]
I chatted with @hokei about this over Slack—I think the only part of this proposal I'm not sold on yet is the Column(s) bit. So far every design I've seen for the system has fallen into one of two categories:

Vertical:
<img width="389" alt="Screen Shot 2020-06-09 at 12 42 18 PM" src="https://user-images.githubusercontent.com/1720093/84175938-a889de00-aa4e-11ea-8032-348b0befb553.png">

or Horizontal, with a three column lockup (third CTA col optional):
<img width="601" alt="Screen Shot 2020-06-09 at 12 44 32 PM" src="https://user-images.githubusercontent.com/1720093/84176137-f868a500-aa4e-11ea-96cb-f9adbad2b3fc.png">

Horizontal, without optional third column:
<img width="667" alt="Screen Shot 2020-06-09 at 12 43 23 PM" src="https://user-images.githubusercontent.com/1720093/84176024-cfe0ab00-aa4e-11ea-9b8f-f15ec09e3d28.png">

For the new Card component, this would give us:
- Optional Header
- Optional Footer
- 25% | 50% | 25% JSX.Element(s) (last col optional)
