### ISSUE TITLE
Import Strategy

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#235]
```
import * as DS from '@nypl/design-system-react-components';

function NewComponent(props) {
  return <DS.Link><Link to="/license">public domain</Link></DS.Link>;
}
```

What's the lift to import individual components instead of *?

**Comment by kristojorg** [comment]
Presumably it would be that the consuming app would only include the components it needs, not the whole bundle. I'm not sure what the full bundle size is of DS, but keeping bundle size down is pretty important for web products
