### ISSUE TITLE
Creating Multidev Environments for Feature Branches

### ISSUE THREAD

**Issue by scooooooooby** [NYPL/nypl-design-system#26]

**Comment by EdwinGuzman** [comment]
Do you mind if I try this with netlify?

**Comment by helenvholmes** [comment]
@EdwinGuzman Don't mind at all! The app is already added to the @NYPL github space, so you should be good to go. Is it possible to create an NYPL account and share that username and password with the Engineering team? Is there like an organizational LastPass or something?

**Comment by EdwinGuzman** [comment]
Yeah, sort of. I'll write it down and then DM you.

**Comment by helenvholmes** [comment]
Closed via #307.
