### ISSUE TITLE
PropTypes area in "Show Info" are missing

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#261]
<img width="1188" alt="No PropTypes appear" src="https://user-images.githubusercontent.com/1720093/86249552-6f401c00-bb7d-11ea-9854-fda570c4fcc4.png">

After hitting the "Show Info" button in Storybook, the PropTypes tables for the component(s) no longer appear (as show in the screenshot above).

**Comment by helenvholmes** [comment]
https://storybook.js.org/docs/configurations/typescript-config/

**Comment by EdwinGuzman** [comment]
Fixed in #275. Closing.
