### ISSUE TITLE
Image fallback

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#267]
### Component in question:
- `Image`

### Description of issue:
- Images should have a background pattern
- CSS-only solution would be ideal 
- Should match crosshatch specified in the [designs](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=11896%3A45379)

**Comment by bigfishdesign13** [comment]
Moved to [DSD-185](https://jira.nypl.org/browse/DSD-185).
