### ISSUE TITLE
NYPL DS giving nypl-footer extra space at the bottom

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#272]
html {
  @include font-settings;
  // Including NYPL DS gave the footer extra space at the bottom.

@scooooooooby do we have a ticket to fix this?

_Originally posted by @hokei in https://github.com/NYPL/nypl-library-card-app/pull/45_

**Comment by EdwinGuzman** [comment]
I think the extra space comes from the rule:
```
html {
    box-sizing: border-box;
}
```

In the library card app, I remove it by adding:
```
html {
  @include font-settings;
  // Including NYPL DS gave the footer extra space at the bottom.
  box-sizing: inherit;
}
```

**Comment by helenvholmes** [comment]
@EdwinGuzman Ah, so previously card-creator was using a different box model?

**Comment by helenvholmes** [comment]
@EdwinGuzman Hey Edwin, is this ticket still valid?

**Comment by helenvholmes** [comment]
Closing out, as this is actually related to the footer itself. See [bug RENO-1661](https://jira.nypl.org/browse/RENO-1661).
