### ISSUE TITLE
Autosuggest

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#278]

**Comment by helenvholmes** [comment]
Unassigning myself while @EdwinGuzman is working through #307.

**Comment by EdwinGuzman** [comment]
I didn't realize you had assigned this to yourself to work on!

**Comment by helenvholmes** [comment]
@EdwinGuzman I think I brought it up in last planning, but I was kind of stuck on how to proceed—I'm really glad you picked up the gauntlet! Originally we were planning on building our own custom Autosuggest and I simply wasn't looking forward to it.
