### ISSUE TITLE
Forwards Link Story Not Displaying as Intended

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#284]
### Component in question:
- `Link`

### Description of issue:
- Various stories are broken

**Comment by EdwinGuzman** [comment]
I've gone through all the stories and haven't found any that are currently broken.

**Comment by helenvholmes** [comment]
@EdwinGuzman Sorry, I'm using "broken" colloquially instead of referring to a broken build. Some of the Link stories are not appearing as intended. I'll update the name.
