### ISSUE TITLE
Breadcrumbs is only ever turquoise

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#301]
### Component in question:
- `Breadcrumbs`

### Description of issue:
- Breadcrumbs should recognize the modifiers for `whats-on`, `locations`, and the other section colors and have its background update accordingly.

**Comment by helenvholmes** [comment]
Blocks [RENO-550](https://jira.nypl.org/browse/RENO-1550).

**Comment by hokei** [comment]
Is this a way to get us to the world where we have design tokens?  Ideally we'd want this configuration to be on a whole-app basis, rather than component-by-component.

**Comment by helenvholmes** [comment]
@hokei I think you're right—the CSS for this should probably be swapped to:

```
.app--locations {
  .breadcrumbs {
    background-color: locations-color
  }
}
```

@misselbeck, this will make your work in Location Finder fundamentally different as an FYI.

**Comment by helenvholmes** [comment]
I've updated the PR to reflect this conversation.
