### ISSUE TITLE
linkType should become type

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#309]
### Component in question:
- `Link`

### Description of issue:
- `Link` currently accepts a `linkType` prop. This should be a `type` prop instead to accommodate for more HTML-ish prop names.
- Update: It's not that the `linkType` prop name should be updated, but the props are being passed directly from the parent to the child and I think a new object should be created. Right now, the `a` element is created through `...linkProps` but there's also a separate `...attributes` prop for any other attributes. This seems redundant.

**Comment by EdwinGuzman** [comment]
@scooooooooby I hope you don't mind me taking this.
