### ISSUE TITLE
Spacing on Main element

### ISSUE THREAD

**Issue by misselbeck** [NYPL/nypl-design-system#342]
### Component in question:
- Full Width Template

### Description of issue:
-  There are certain screen widths (in the desktop breakpoint) where the padding on the Main element no longer applies and the page items hit the edge of the screen.
- Additionally whitespace is added on either side of the content-top when it sound be a break-out.

![main-padding](https://user-images.githubusercontent.com/1325185/90529900-3a465380-e142-11ea-897e-2923566347b3.png)

**Comment by helenvholmes** [comment]
PR linked. 

The only part of this that ultimately was WONTFIX is the content-top being a breakout—we have a space called "hero" for that.
