### ISSUE TITLE
IE11 strategy

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#344]
### Component in question:
- all

### Description of issue:
- We should document what our supported browsers are.  
- For IE 11, to what extent should we support it?  NYPL does not care as much about visuals as they do about functionality in IE 11.  
- To what extent should we offer guidance on how to override things that don't work in IE 11?  (eg: CSS variables). 
- For IE 11, getting `SCRIPT1002: Syntax error` on any page that imports DS. Javascript will break on the page, because arrow functions are included in the DS dist package.

**Comment by andrewnshelton** [comment]
Closed via #350 and #351
