### ISSUE TITLE
Regression Testing

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#345]
### Component in question:
- All

### Description of issue:
- Holder for eventual regression testing work.  
- Goal:  Have an automated way to be alerted when regressions happen
- This may contain:  Automated testing in multiple browsers
- snapshot testing

**Comment by helenvholmes** [comment]
@hokei, this sounds like a project, not a bug, exactly. Can we close this out until the project is on the roadmap?

**Comment by helenvholmes** [comment]
Closing this out as it's an entire project that needs to be prioritized on our [roadmap](https://app.smartsheet.com/sheets/9hC7JwMfgWFV9vfx7hJm5mF8gvJ3phq9JjPHCGg1?view=gantt).
