### ISSUE TITLE
Test needed for Storybooks "Show Info"

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#359]
![Screen Shot 2020-08-25 at 10 11 04 AM](https://user-images.githubusercontent.com/1720093/91187602-573cd280-e6be-11ea-94c1-255510522025.png)

"Show Info" consistently breaks without people being aware of it. We should add a test of some sort to know if/when our work is breaking the Storybook show info panel.

**Comment by EdwinGuzman** [comment]
Context - might have to do with react's `forwardRef` implementation of components.
