### ISSUE TITLE
SVG props being applied to wrapping span, not SVG directly

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#366]
### Component in question:
- `Icon`

### Description of issue:
- A number of props being passed to `Icon` that I would expect to see on the `<svg>` tag are instead applied to the wrapping `<span>` element, causing bugs like #360.

**Comment by helenvholmes** [comment]
Related to #414.

**Comment by EdwinGuzman** [comment]
I think there are a couple of issues here.
1. The [`iconsProps` object](https://github.com/NYPL/nypl-design-system/blob/development/src/components/Icons/Icon.tsx#L84) contains the `role` and `title` attributes which should go to the svg element and not the `span` element on lines 106 and 109.
2. There should be a new object called `svgProps` that contains those attributes.
3. A larger issue might be that the svgs are all being rendered directly as svg through `dangerouslySetInnerHTML `. That means that the svgs are not React components and can't take in those props.
4. The `title` prop should not be added to the svg as `title={title}` but rather `<title>{title}</title>`.

**Comment by EdwinGuzman** [comment]
This might be blocked by the svgs not being components but not sure if we want to turn them into components.

**Comment by helenvholmes** [comment]
> This might be blocked by the svgs not being components but not sure if we want to turn them into components.

@EdwinGuzman I think this is right. The numbered list you have is all correct—we want those props on the `svg` element itself, not on the wrapper outside of it.

**Comment by andrewnshelton** [comment]
Moved to JIRA as DSD-87

**Comment by bigfishdesign13** [comment]
Closing this issue, as it is now being tracking in [DSD-87](https://jira.nypl.org/browse/DSD-87).
