### ISSUE TITLE
Add resizeable button story

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#385]
### Description of task:
Add controls to `Button` component to affect interior size of content.

- Should wrap the text in a block element with a controllable width and height.
- Should keep text centered both horizontally and vertically.

[See "button groups" here for design.](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=11477%3A2298)

### Component in question (if applicable):
- `Button`

**Comment by andrewnshelton** [comment]
Moved to JIRA as DSD-88
