### ISSUE TITLE
Netlify CI runs on release PRs

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#408]
### Description of issue:
- Netlify serves up our multidev environments.
- We only get so many multidev environments a month before we have to pay.
- We create multidev environments for release PRs, which (so far) hasn't been necessary. 
- Cutting out the multidev generations on these PRs should help prevent us from hitting limits in the future.

**Comment by helenvholmes** [comment]
For additional context, @EdwinGuzman got this set up for us and Netlify is set up under the NYPL digital email.

**Comment by andrewnshelton** [comment]
Requires follow-up with Edwin

**Comment by EdwinGuzman** [comment]
We haven't reached the limit or have gotten close to it so this isn't an issue _yet_. I think it's set up to only create a dev environment for pull requests and if we cut out multidev generations, then we won't get anything out of this. Unless if we are planning or hoping to use Netlify for something else.

**Comment by helenvholmes** [comment]
I think we got close _once_, but I am dubious we're ever going to run into the limit again now that we're not doing as much intense active development on this. I'll close this out.
