### ISSUE TITLE
Global tests

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#41]
Some tests that would be nice to run before every merge:   Could be a pre-commit hook, could be travis.

- A sanity script that spins up storybook for both twig and react and makes sure that they aren't broken
- A linter that verifies the file structures on styles/twig/react and makes sure they are the same
- Something that runs `npm test` in all the repos

**Comment by helenvholmes** [comment]
@hokei can you verify that this has been completed/answered? I'm not actually certain what our Travis build does currently...

**Comment by hokei** [comment]
@scooooooooby I think we can close this.  Our travis build currently runs test in all the repos, we don't need to verify file structure any more.  I'd love to have sanity tests for storybook but I think they should go inside npm test rather than in travis.

**Comment by helenvholmes** [comment]
Closing this out then. Thanks Crystal!
