### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#410]
### Description of issue:
- [link to designs](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=12910%3A52412)

### Component in question (if applicable):
- New component | [documentation](https://inclusive-components.design/tabbed-interfaces/)

**Comment by EdwinGuzman** [comment]
If possible, can the current Tabs component from the NYPL-Simplified [reusable-components](https://nypl-simplified.github.io/reusable-components/?path=/story/components-tabs--with-items)  repo be used for the foundation code? Adriana already wrote a lot of accessible code for it but now it's a matter of implementing the new style.

**Comment by helenvholmes** [comment]
@EdwinGuzman I think that's a fabulous idea. Can I ask if that code has any relationship to the [Heydon Pickering inclusive component](https://inclusive-components.design/tabbed-interfaces/) for tabs?

 The designs aren't solidified, so pulling those over as-is feels like a great answer regardless of the answer to the above. Edwin, would you be willing to pull those over?

**Comment by EdwinGuzman** [comment]
Oh I'm not sure if the code is based on that but that looks like a good resource. I don't mind pulling over the code but, @adriana-alter do you want to try this if you're not busy? I don't think there's a rush so no pressure, but seeing as you wrote it maybe you'd want to move it.

**Comment by adriana-alter** [comment]
Absolutely (and thanks for looping me in)!  I'll try to get it into the next sprint.

**Comment by helenvholmes** [comment]
> Absolutely (and thanks for looping me in)! I'll try to get it into the next sprint.

Rad! I'm going to tag you on the ticket then.

**Comment by helenvholmes** [comment]
Duplicate of [UX-212](https://jira.nypl.org/browse/UX-212)
