### ISSUE TITLE
Definition List

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#411]
### Description of issue:
- [link to designs](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=10734%3A5178)

### Component in question (if applicable):
- New component | [documentation](https://inclusive-components.design/data-tables/)

**Comment by hokei** [comment]
the Inclusive Components page:  https://inclusive-components.design/data-tables/

**Comment by helenvholmes** [comment]
Duplicate of [UX-121](https://jira.nypl.org/browse/UX-121)
