### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#412]
### Description of issue:
- [Designs](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=17519%3A64445)

### Component in question (if applicable):
- New component

### Metronome Documentation
- [SCC Support Components, expand `Dropdown`](https://airtable.com/shrnoS9AtWEPcFJFo)

### Additional Inclusive Design Article
[Heydon Pickering](https://inclusive-components.design/menus-menu-buttons/)

**Comment by hokei** [comment]
Assuming the difference between "Dropdown" and "Accordion" is that 
Dropdown's children float above the content, while Accordion's children pushes the content down:  

Dropdown becomes Accordion in mobile:  https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main


There are two ways to tackle this: 

1) An API that goes
```
{isMobile && <Accordion>{Content}</Accordion> } {isDesktop && <Dropdown>{Content}</Dropdown>} 
```

2) An API that goes 

```
<Accordion shouldContentFloat = isWidescreen> {Content} </Accordion> 
```

for "Dropdown" and 

```
<Accordion> {Content} </Accordion> 
```

for "Accordion"

I think option 2 is more correct, meaning I think this should be a re-write of the "accordion" component, rather than making a new "dropdown" component.  

Thoughts?

**Comment by helenvholmes** [comment]
> I think option 2 is more correct, meaning I think this should be a re-write of the "accordion" component, rather than making a new "dropdown" component.
> 
> Thoughts?

I think this is the smarter direction from a technical standpoint, but on a practical standpoint I think it will cause confusion. We've put in a lot of work to have React components to be one-to-one to Metronome entries to be one-to-one to Figma components. [IBM Carbon](https://www.carbondesignsystem.com/components/dropdown/code/) makes a distinction between these two components as well, which is what we're looking to for guidance here—they're intended to be used in different situations, for different things.

I hope that clarifies the reason for this direction. I agree that the mobile similarity to Accordion leaves something to be desired, but I think this gives us the room to improve on this component in the future without having to guide developers through a migration guide if we end up deciding to split them at a future date.

**Comment by helenvholmes** [comment]
cc @wluisi @siberry (whoever ends up building this), everything for the component is spec'd out (including some pseudo-code that Crystal's provided) here.

**Comment by siberry** [comment]
@scooooooooby @wluisi working on this component is on my board for this sprint :) Getting back to it right now!

**Comment by helenvholmes** [comment]
Closed in favor of [UX-220](https://jira.nypl.org/browse/UX-220).
