### ISSUE TITLE
Autosuggest story on Storybook hard to see

### ISSUE THREAD

**Issue by siberry** [NYPL/nypl-design-system#429]
### Description of issue:
- For the [Autosuggest stories](https://nypl.github.io/nypl-design-system/storybook-static/?path=/story/autosuggest--autosuggest-library), the suggestions are hidden by the container, making this component hard to decipher. You have to scroll within the container to see them.

### Component in question (if applicable):
- Autosuggest

### Figma Link (if applicable):
- https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=11689%3A423

**Comment by EdwinGuzman** [comment]
Oh yeah, it seems there was a change and now the suggestions aren't showing.
