### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/nypl-design-system#431]
### Description of issue:
- Similar to #350, there are a few IE11 issues. Here's a screenshot from Windows 8.1 using IE11:
<img width="1277" alt="Screen Shot 2020-11-18 at 8 37 31 AM" src="https://user-images.githubusercontent.com/1280564/99537337-88edce80-2979-11eb-93aa-11a2c5847bd4.png">

It looks like some CSS rules to align the Hero content isn't working and the styles for input elements aren't being applied. Pointing this out but might be hard to debug and also, IE11...

### Component in question (if applicable):
- Hero, Input

**Comment by helenvholmes** [comment]
Hey @EdwinGuzman, based on yesterday's FED monthly I'm closing this and #350 out.

**Comment by EdwinGuzman** [comment]
:rocket:
