### ISSUE TITLE
Revise Status Badge Component

### ISSUE THREAD

**Issue by nypl-wluisi** [NYPL/nypl-design-system#434]
### Description of issue:
- Revise the StatusBadge to be an actual component that accepts props, and could be used like this:

```
// Renders gray
<StatusBadge type={'notice'}>Registration Required</StatusBadge>

// Renders yellow
<StatusBadge type={'alert'}>Cancelled</StatusBadge>
```

- [ ] Add the StatusBadge component
- [ ] Integrate with Storybook
- [ ] Write basic tests

Looks like this:

<img width="238" alt="statusBadge" src="https://user-images.githubusercontent.com/62392174/99568747-c06e7200-299d-11eb-8528-3759d9a6308b.png">

### Component in question (if applicable):
- Status Badge

### Metronome Link (if applicable):
- [Metronome](http://themetronome.co/components/mt-345-status-badge/?fresh=true)

### Figma Link (if applicable):
- [Figma](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=11256%3A0)

**Comment by helenvholmes** [comment]
Updated the design link.
