### ISSUE TITLE
Checkbox sizing inconsistent on Safari

### ISSUE THREAD

**Issue by siberry** [NYPL/nypl-design-system#443]
### Description of issue:
- On Safari, iPhone 6s Plus (Ellen's phone) and iPhone 7 (mine), probably others as well, checkboxes do not remain the same size depending on the content of the label.
![checkboxes](https://user-images.githubusercontent.com/47210101/100141557-a1ba2080-2e60-11eb-957a-8ff371e7c5e5.PNG)
Example: http://qa-discovery.nypl.org/research/collections/shared-collection-catalog/bib/b11483389

This is fixed by removing `display: flex` from `.checkbox`

### Component in question (if applicable):
- Checkbox

### Metronome Link (if applicable):
- [Metronome](XXXXXX)

### Figma Link (if applicable):
- [Figma](XXXXXX)

**Comment by andrewnshelton** [comment]
We should make a story thats a list of checkboxes (per DS Sprint Planning discussion 1/7)

**Comment by andrewnshelton** [comment]
Moved to JIRA as DSD-89
