### ISSUE TITLE
Styling error in SearchBar

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#445]
### Description of issue:
- The search button's icon is [looking pretty wonky](https://nypl.github.io/nypl-design-system/storybook-static/?path=/story/searchbar--search-bar):

![Current searchbar](https://user-images.githubusercontent.com/1720093/100641486-85f1c700-3305-11eb-910a-3e1c9540b3ff.png)

### Component in question (if applicable):
- `SearchBar`

**Comment by andrewnshelton** [comment]
Moved to JIRA as DSD-90
