### ISSUE TITLE
Feature: Lazy Load Images

### ISSUE THREAD

**Issue by kristojorg** [NYPL/nypl-design-system#446]
### Description of issue:

This is a feature request to lazy load offscreen images. It can be done using the `IntersectionObserver` api so that images are only downloaded once they reach some distance from the viewport. This makes first render much faster as the browser only has to download visible images. It's especially useful in image-heavy apps like DRB or CPW. 

There are many open source components our there that do this, and I would suggest looking at them to see if they can simply be imported, or at least learned from. 

Common features:

- Fallback to load everything for IE
- Have an image placeholder for while the image is loading, in case the user scrolls too fast. This allows the layout to not jump when images come in.

### Component in question (if applicable):

- Image

**Comment by helenvholmes** [comment]
We have some nice "decorative" icons that could be nice fallbacks [here](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=10968%3A1918), or potentially we could use some of the CSS that @nypl-wluisi wrote for the `SkeletonLoader` here.

**Comment by hokei** [comment]
I imagine this is the most useful for book covers, so the book icon would probably be good!  Though it probably makes the most sense to pass in a fallback icon?

**Comment by andrewnshelton** [comment]
Moved to JIRA as DSD-91
