### ISSUE TITLE
Icon - No "undefined" values for missing props

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/nypl-design-system#448]
### Description of issue:
- If some props are not passed to the `Icon` component, then `undefined` is added as a value to that HTML attribute. It should be `null` instead.

Example:
In `Icon.tsx` line 88 -

```
"aria-labelledby": title ? "title-" + name : undefined,
```

renders:

```
<span className="icon icon--small icon--minus " aria-hidden={true} aria-labelledby={[undefined]} ... />
```

### Component in question (if applicable):
- `Icon`

**Comment by andrewnshelton** [comment]
Move to JIRA as DSD-92
