### ISSUE TITLE
Deprecate `DefaultChecked` in Checkbox

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#455]
### Description of issue:
- We should provide and recommend controlled components, as is React best practice.  In the next breaking change (0.5.0), remove the uncontrolled version of checkbox. 

### Component in question (if applicable):
- Checkbox

### Metronome Link (if applicable):
- none

### Figma Link (if applicable):
- none

**Comment by hokei** [comment]
@wluisi let me know if this sounds right/sane?  I am still kinda learning React best practices piecemeal haha. 

@scooooooooby I added the `0.5.0` label for us collect stuff for the next breaking release.  Let me know if there's a better place to put this.

**Comment by helenvholmes** [comment]
> @scooooooooby I added the `0.5.0` label for us collect stuff for the next breaking release. Let me know if there's a better place to put this.

Mind if I change this to something like "Next breaking release", or something like that? We're at `0.18.5` release-wise so the label doesn't feel very descriptive currently

**Comment by hokei** [comment]
OH DARN HAHA WOW yes of course. Clearly I have not been keeping track of the releases.  
I'm gonna be happy once we hit 1.0 and then this will all be really clear!

**Comment by hokei** [comment]
Based on the conversation here: https://github.com/NYPL/nypl-design-system/pull/413#discussion_r534243346 we will not do this.
