### ISSUE TITLE
Github and NPM versions out of sync

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#460]
### Description of issue:
- Github's latest release is 0.18.2, whereas it should be at 0.18.6 (which is appearing on NPM). I assume something is misfiring in our Github Actions...

**Comment by EdwinGuzman** [comment]
This was fixed in PR #463 .
The latest release is available [0.18.6](https://github.com/NYPL/nypl-design-system/releases/tag/v0.18.6).

**Comment by EdwinGuzman** [comment]
I'm not sure if you want to retroactively create releases for versions from 0.18.3 to 0.18.5. If so, this can be kept open until those are created.

**Comment by helenvholmes** [comment]
We probably should, I think.
