### ISSUE TITLE
Document what should go in a story

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#482]
### Description of issue:
- It's not clear right now what stories are for.  Most stories detail visual differences, but `Link` stories are also code examples on how to use `Link` in specific circumstances
- `Checkbox` stories seem to re-explain what the difference is between controlled and uncontrolled components
- Let's discuss how we want stories to work, and document this in the wiki.

**Comment by hokei** [comment]
High level topics:  

- Stuff that's covered in React documentation, such as how to use controlled and uncontrolled components - should these go in stories?  
- It makes sense for stories to mostly be visual, but the `Link` router documentation is actually very useful, in lieu of having a set of example applications 
- Maybe a story that's not tied to a component about how to use components in different situations?

**Comment by EdwinGuzman** [comment]
It's been discussed that DS should be a project that sets standards, best practices, etc in NYPL Digital. With that in mind, trying to cover as much as possible for devs is a good idea. Specifically, if we need to reiterate what's in the official React documentation, we can do so but also link to the more extensive documentation.

I mostly imagine DS' Storybook to be similar to this from [Reaviz](https://reaviz.io/?path=/story/docs-getting-started-data-shapes--page) (which was showcased in this [blog post](https://medium.com/storybookjs/rich-docs-with-storybook-mdx-61bc145ae7bc) from Storybook). The example is comprehension - it shows types, code, documentation, how to use it, a live example, etc. This Storybook also uses [mdx](https://storybook.js.org/docs/react/api/mdx) which might also help us write better stories and documentation.

It's hard to say exactly what the right amount of documentation is needed for any component but with what we currently have we have discussions around how a component should be used. It seems like having more might help with this issue.

**Comment by helenvholmes** [comment]
I've created a ticket in the UX backlog to create a list of required documentation per component. I've linked to this discussion but will be closing out the ticket in favor of [UX-213](https://jira.nypl.org/browse/UX-213).
