### ISSUE TITLE
Autosuggest story documentation

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#495]
### Description of issue:
- as a developer working with the Design System, it is unclear that `Autosuggest` works differently from the rest of the components and should be considered a guideline on how to implement `react-autosuggest` rather than a story that is to be imported
- We should document this, and provide an easy-to-copy code-block for users who want to implement Autosuggest.  
- This could be a good way to start introducing [mdx](https://storybook.js.org/docs/react/api/mdx) to storybook

### Component in question (if applicable):
- autosuggest

### Metronome Link (if applicable):
- [Metronome](XXXXXX)

### Figma Link (if applicable):
- [Figma](XXXXXX)

**Comment by helenvholmes** [comment]
Closing as dup of https://jira.nypl.org/browse/UX-238
