### ISSUE TITLE
Select with Autocomplete component 

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#501]
### Description of issue:
- There is a pattern that seems to pop up - a list with many items (library locations, available languages) that might go in an `autosuggest` component, but also might go in a component that looks a little like the third example here: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
- Should this be a new component?  

### Component in question (if applicable):
- New component, maybe? 

### Metronome Link (if applicable):
- [Metronome](XXXXXX)

### Figma Link (if applicable):
- [Figma](XXXXXX)

**Comment by hokei** [comment]
Nothing specifically calls for it right now, but [DRB](https://themetronome.co/components/of-27-advanced-search-form/) mocks currently call for a `Select` with 50+ options, so that doesn't seem great either.

**Comment by helenvholmes** [comment]
Closing as dup of https://jira.nypl.org/browse/UX-236
