### ISSUE TITLE
Generic keynames in Pagination

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#502]
### Description of issue:
- In `Pagination`, item [here](https://github.com/NYPL/nypl-design-system/blob/development/src/components/Pagination/Pagination.tsx#L79) is often a number.  
- App developers often have numbers as keynames (they shouldn't, but it's a common mistake).  I think it's best to rename this just to get out their way.  

### Component in question (if applicable):
- pagination

### Metronome Link (if applicable):
- [Metronome](XXXXXX)

### Figma Link (if applicable):
- [Figma](XXXXXX)

**Comment by helenvholmes** [comment]
Closing as dup of [UX-234](https://jira.nypl.org/browse/UX-234)
