### ISSUE TITLE
Pull together documentation for Michael

### ISSUE THREAD

**Issue by andrewnshelton** [NYPL/nypl-design-system#503]
Review:
- [ ] [README](https://github.com/NYPL/nypl-design-system/blob/development/README.md)
- [ ] [Wiki](https://github.com/NYPL/nypl-design-system/wiki)
- [ ] [Outstanding PRs](https://github.com/NYPL/nypl-design-system/pulls)
- [ ] Assigned backlog tickets

Update:
- [ ] [README](https://github.com/NYPL/nypl-design-system/blob/development/README.md) to include note on who current maintainer is (Michael, Helen) so contributors know who to add to reviews
- [ ] [Approvals section](https://github.com/NYPL/nypl-design-system/wiki/Contributing-to-the-React-Library#who-does-approvals) in wiki to reflect new maintainer

Create:
- [ ] Maintainer page on [wiki](https://github.com/NYPL/nypl-design-system/wiki) with @hokei's notes on maintainer responsibilities

**Comment by helenvholmes** [comment]
Gave this a shot, @hokei. Anything else you think we need to include? (Obviously I'll work to get Michael assigned some starting tickets, but @andrewnshelton and I will do that in a meeting next week.)

**Comment by hokei** [comment]
Jotting down some things I think we should cover (But I'm not sure where it should be written down) 

The maintainers' responsibilities are (in this order) 
- Answering implementation questions in the Design System channel 
- Reviewing PRs into the Design System 
- Addressing bugs/documentation requests/etc
- Ensuring README and wiki documentation are up-to-date
- Coordinating and running releases

The maintainer should be assigned to all PRs, but if they make PRs (bugfixes, etc) the reviewer should be the person who filed the issue

**Comment by hokei** [comment]
maybe a staff page on the wiki?  For some reason I vaguely remember a "where to go for help" page but I can't seem to find it

**Comment by helenvholmes** [comment]
> maybe a staff page on the wiki? For some reason I vaguely remember a "where to go for help" page but I can't seem to find it

Maybe this? https://github.com/NYPL/nypl-design-system/wiki/Contributing-to-the-React-Library#who-does-approvals

EDIT: (I like the idea of a Staff Page a lot, though.)

**Comment by helenvholmes** [comment]
Filed [UX-224](https://jira.nypl.org/browse/UX-224), [UX-225](https://jira.nypl.org/browse/UX-225), and [UX-226](https://jira.nypl.org/browse/UX-226).
