### ISSUE TITLE
How often will we expect consumers to want to do experiments driven by product with no UX input?

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#78]
ResearchNow wants to do this:  https://jira.nypl.org/browse/SFR-89

This requires putting in a link in the no-download-links case, which requires actually changing stuff in the design system.  Right now, since it's me, I can do that, but how do we do something like this going forward?  Is it reasonable to say "you can't" or is there a way we can make the design system flexible enough to accommodate something like this?

**Comment by helenvholmes** [comment]
@hokei I can answer this question from a UX perspective, which is... we hope never.

The UX team is really hoping to get NYPL to stop doing user flow testing on code (at least until getting simply prototype flows up and running with the design system is relatively easy).  We believe Figma prototypes are a better alternative as they can be built out much faster. We hope testing on code in the future will be for identifying last nits.

Going to close this out for now.
