### ISSUE TITLE
Add story for card_grid.scss

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#88]
### Component in Question
- [card grid scss](https://github.com/NYPL/nypl-design-system/blob/development/src/styles/base/_card-grid.scss)

### Description of Ticket
Add a story that shows off functionality of card_grid.scss.

- Controls should allow users to add/subtract cards

**Comment by helenvholmes** [comment]
@hokei, this sounds like another one that might belong on SFR's board—if we can verify later that this is needed in DBR we should track it there as it's new work.

**Comment by helenvholmes** [comment]
This could be just documentation about how to set up your page

**Comment by helenvholmes** [comment]
https://gist.github.com/scooooooooby/1228d61641389ff4540b43fd5e347a55

**Comment by bigfishdesign13** [comment]
Moved to [DSD-187](https://jira.nypl.org/browse/DSD-187).
