### ISSUE TITLE
Github-specific Setup

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#9]
Part of setting up this repo includes: 

- [x] Vetting the labels
- [x] Adding a PR template
- [x] Adding an issue template
  - [x] We have the tasks of ongoing work (captured in project-specific Jira boards)
  - [x] We have the ongoing research tasks associated with this project
  - [x] We have issue templates that we'll need when people begin using the library
    - [x] We'd like to see what CSS overrides library consumers have written, for example, and a prompt to explain why they authored those changes and what project-specific problems this fixed
- [ ] ~Setting up Wikis and relevant containers for documentation~ not finished but closing in favor of #44
- [x] Which folders can safely be gitignored?

**Comment by hokei** [comment]
Probably related to this:
https://github.com/NYPL/nypl-design-system/projects/1#card-28065649
