### ISSUE TITLE
Add External Link-Type to Link

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#95]
### Component
- `Link`

### Description of issue:
- `Link` should be updated to include the design for an external link with `rel=nofollow` as illustrated [here](https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Master?node-id=16115%3A407).

**Comment by helenvholmes** [comment]
@hokei, can you verify this is needed in DBR? If so I'd like to get a ticket on that board instead of this one for this work, seeing as we don't have designs for it yet.

**Comment by helenvholmes** [comment]
@hokei to create DBR ticket, Helen to add designs, related to #122

**Comment by bigfishdesign13** [comment]
Moved to [DSD-186](https://jira.nypl.org/browse/DSD-186).
